from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd

# Connect to an existing Chrome instance with debugging enabled
options = webdriver.ChromeOptions()
options.debugger_address = "127.0.0.1:9222"
driver = webdriver.Chrome(options=options)


names = """
Nesim Hason
Michelle Moore
Paco Gratacos
Jonathan Shrank
Daniel Garcia
Pablo Perel
Daniel Djahjah
Carolina Padula
Cecilia Gomez de la Torre
Alberto Perez de la Mesa
Victoria Bitar
Samantha Martinez
Andres Romero
Ariel Graizer
Ettore Botta
Silvana Dangelo
Agustin Fabregues
Liliana Chavez
Rene Leda
Tania Benitez
Eugenia (Yuyi) Cardenas
Miguel Somoza
Selina Nederhand
Gustavo Aparicio
Luis Guillermo Camacho
Neil Maman
Eduardo Ruiz
Hortensia Montesino
Ana Alvarado
Valeria Palazzio
Martin Mariani
Daniella Piquet
Luciano Molina
Samuel Duque
Adolfo Alvarez Rivas
Pablo Orden
Diana Figueroa
Brandon Montgomery
Olubunmi Abejirin
Emmanuel Odole
Elisa Brough
Greg Brough
Dmitry Poyurovskiy
Rosario Buil
Claudia Bouche
Luis Daniel Capriles
Gisell Maynoldi
Juan Diego Garreton
Hortensia Quadreny
Roberto Rosales
Adam Rumanek
Peter Bellorin
Adela Redondo
Steven Hoyt
Doug Butts
Ken Reiner
Vlad Grayvoronskiy
Warren Campbell
Lynn Miteva
Rosemarie Morales
Michael Igwe Esione
Andres Mendoza
Susana Umbert
Andres Badra
Angela Sondon
Amanda Lestayo
Laxmi Lorenzo
Marisol Amaya
Gregorio Gonzalez
Keren Varela
Prashant Chothani
Jason Nader
Neelakandan Satheeis 
Erika Vogt-Lowell
Guillermo Sierra
Yanai Arfi
Kelly Palmatier
Yolanda Choates
Lou Martinez
Maria Lucia Gil
Analida Lopez
Marcela Gonzalez
Nyasha Muzavazi
Natasha Janson-Kline
Jessica Rodriguez
Chauncey Smith
Aden Ikram
Cyrus Farrokh
Craig Ferguson
Josh Rosenblatt
Daniel Hernandez
Renzo Tamariz
Ben Zurier
Daniel Thompson
Linda Curtis
Bill Curtis
Yanaice Ojito
Cat Zappa
David Israel
Gregory Kimmelman
Alexia Melocchi
Francesc Gratacos
David Henden
Aldo Di Felice
Karen Chin
David Katz
Debbie Back
Dana Webber
Alina Pakhaeva
Dina Lee Almeida
Katherine Weinstein
Cristina Guggino
Jonitha Keymoore
Jamie Schouela
Marie Leguizamo
Manuel Miguez
Marina Khabarova
Theresa Patiri
Kobina de Graft-Johnson
Stan Hum
Larry Verbit
Scott Herbst
Melissa Wohl
Katie Keenan
Javiera Balmaceda
Javier Pons
Hasret Ozcan
Katherine Pond
Harry Gamsu
Greg West
David Hooper
Leyla Rosario
Kathryn Hubbard
Greg Moyer
Harvey Grisalez
Reginald M. Jernigan Jr.
Christiana Becerra
Senta Menger
Rich Wolff
Susan Helfrich
Rachel Falleroni
Kiran Sachdeva
Cindy Wallis
Andreas Olavarria
Benjamin Bezold
Lisa Fox
Greg Rubidge
Charlie Lubiniecki
Scott Grainger
Ashley Cabulagan
Marty Patch
Alexis Iraq
Colby Gaines
Jennifer Comeau
Melissa Campbell
Danny Wilk
Jonathan Loew
Daniel Oron
James Boyd
Lauren Menkes
Beverly Thomas
Richard Perry
Holly Cowdery
Laurent Zameczkowski
Manjyot Sandhu
Michele Arteaga
David Barski
Willie J. Hernandez
Caleb Eckhardt
Kyle Whited
David Karabinas
Gene George
Frann Martins 
Lauren Billingsley
Anthony Layser
Keith Alexander
Max Levine
Lefteris S. Eleftheriou
Bob Gruters
Lynwood Bibbens
George Sealey
Jean Uliczay
Aaron Jackman
Marlene  Hochman 
Tracy West
Robert Franke
Nan Halperin
Madelyn Cunningham
Lee Vanacore
Emma Smith
Rachel Goldman
Mariano Roson
Darren Melameth
Lydia Yamina Segundo
Neal Sabin
Lily Caputo
Sophia Kelley
Rob Kaplan
Jin Woo Hwang
Robert Brooks
David Padilla
Nicholas Paleveda
Branden Tinsler
Andrew Tew
Lori Conkling
Gregory Liccardi
John Rossiter
Christopher Poole
Hans Mahr
Gulce Oksuz Cekin
Sriram Chandrasekaran
Sonia Fleck
Mikiko Nishiyama
Ra Kumar
Kevin Hill
Sally Habbershaw
Brett Dismuke
Thomas Dey
Jennifer Daly
Donovan Chan
Allison Wallach
Greg Barnard
Lily Schaer
Steven Love
Julio Sobral
Marc Rashba
Olga Bryant
Amish Rambhia
Pejman Partiyeli
Michelle Romero
Olimpia Ciribe
Alexa De la Cruz	
Matteo Rolleri
Mike West
Maria Rueda
Patrick Morell
David Eilenberg
Rochelle Brown
Kurt Spenrath
Adrienne Hall
Sophie Morgan
Maria Ibarra
Eli Brown
Jaimi West
Miles Jarvis
Dmitry Poyurovskiy
Pamir Demirtas
Sasha Martinez
Vlad Reznikov
Ilan Sarfati
Lydia Horman
Aimee Shimmin
Ross Lewis
John McVay
Tiffany Tulba
Elizabeth Bannan
John Christian Hughes
Gerard Raiti
Marc Leonard
Sagar Khemani
Parker Bova
Vicki Liao
Andrea Brakke
Chantel Miller
Aisha Pinkney
Joe Rivadeneira
David Apostolico
Amy Bennett
Samantha Richardson
Sam Heard
Gabriela Guevara
Amy Eppolito
Kayleigh Mize
Emilia Nuccio
Daniel Gagliardi
Danny Fisher
Damaso Santana
Douglas Zwick
Feliciano Rubiera
Geoff Clark
Hector Campos
Crissie Miller
Courtney Paige
Georgia Rippin
Mariah Larocque
Jeremy Lunt
Angela Chase
Stefan Van Engen
Adam Dukes
Michael Markwell
Michael MacMillan
Cesar Diaz
Juan Carlos Sanchez
'River' Jordan Easton
Elliot Wagner
Madison Wojciechowski
Dan Menzel
David C. Graber
David Decker
Charlotte Thorp
Wayne Lepoff
Fede Goldenberg
Richard Jean-Baptiste
Ryann Lauckner
Grace Moss
Robyn Lattaker-Johnson
David Cornwall
J.C. Mills
CJ Yu
Tiffany Brown
Brie Bryant
Bree Frank
Mark Balsam
Laura Palumbo Johnson
Jason Fox
Matthew Ostrom
Monique Barrett
Geoffrey  Okol
Farah Qayum
Will D'Epagnier
Mat Levy
Mohammed Adnan
Kyle Espinosa
Lauren Zalaznick
Naz Mantoo
Tai Hanson-Shin
Anna-Kay Thomas
Kelsey Griffin
Natalie Vinet
Kimberly Calhoun
Eric Hoberman
Steve Michaels
Peter Andrews
Miguel Rosenfeld
Connie Hodson
Richard  Young
Michela Giorelli
Brad Beale
Kevin Beggs
Dan Cohen
Brandon Brito
Johanna Eliot
Joseph DeBenedictis
Mel Quintans
Pablo Zuccarino	
Tina Rodriguez
Moises Chico
Leslie Miller
Matt Creasey
Isaac Zea
Lyndon Umali
Avi Armoza
Marisa Lloreda
Daniel Barrios
Sebastian Palmadessa
Jennifer Askin
Ayn Prince
Dimiter Nikolov
Carlos Cusco
Stephan Morris
Savannah Pfister
Kimberly Byler
Darren Byler
Luke Kelly-Clyne
Sarah Timoney
John Zaccario
Mal Stares
Betsy Beers
Anne Kennedy McGuire
Michael John Carpiniello, MD
Heidi Cayn Friedman
Sara Burns
Melissa Gonzalez Calvino
Leonidas Oxby
Bill Dever
Antonio Azzalini
Victoria Unikel
Gene Avakyan
Phoenix Gonzalez
Ken Clark
Maggie  Salas- Amaro
Jacob Nasser
John Kiser
Ravi Kapur
Lauren Frasca
Justin Jones
Eric Stein
Sachin Gokhale
Carrie Eckhardt
Mitch Mallon
Sandrine Durand
Teresa Rader
Seth Kittay
Kyle Kaczmarek
Heather Wyer
Nick Lalonde
Joseph Azarian
Juan Fernandez
Andrea Harrick
Roxanne Pompa
Scott Barnett
Beth Anderson
Sarah Shriver
Jaqueline Hall
Lawrence Szabo
Jeff Carr
Jeremy Griffiths
Jessica Mathis
William Graff
Lise Romanoff
Gary Auerbach
Ana Ramírez
Jared Caplan
Michael Schmidt
Chris Philip
Francois Martin
Craig Junner
Nanci Maclean
Scott McGillivray
Julie Auerbach
Katie Buchanan
Celia Tait
Jacqueline Pitman
Marrysa Moyer
Chris Regina
Rich Robinson
Daniel Bort
Haohong Wang
Michael Gelman
Deniz Tuzun
Diane  Tripp
Olga Zharinova
Todd Holzman
Sonia Armstead
Sophie Sandoval
Steven Katleman
Hollie Abbott
Christian Gamboa
Monica Gorghetto
Larry Adkins
Luis Polanco
Dom Serafini
Diego Alfagemez
Fernando Calvino
Stanislav Kimchev
Simone Boyce
Simon Kennedy
Saraa Kami
Kelly Day
Rebecca Glashow
Elaine Frontain Bryant
Brett Hughes
Marc Lee
Adam Steinman
Scott Kirkpatrick
Ryan Swenar
Dominic Gaziano
Timothy Olague
Richard Life
Jens Richter
Alissa Knight
Rogerio Luiz Dallemole
Erika Kennair
Mark Bishop
Brian Tannenbaum
Catherine Zhang
Jonathan Saba
Richard Middleton
Deep Hegiste
Alice Redman
Jessica Atkins
Jennifer Moscat
Don Montierth
Alok Ranjan
Marc Bruder
Eli Lipnik
Karen Juliao
Lisette Osorio
Beej Gefsky
Cris Abrego
Chris Rubi
Bianca Lyndaker
Lauren Behar
Khris Lorenzo
Patricia Sims
Tracia Ord
Jonathan Kramer
Matt Rotondo
Hernan Seoane
Andres Woodhouse
Philip Hopkins
Courtney Kensington
David Rimawi
Nicole Silveira
Liz de Nesnera
Lisette Schlippe
Alara Kolat
Alex Hadad
Minda Long
Farook Singh
Judy Barlow
Luis Fernandez
Roko Izarra
Marco Giron
Lesley Apelbaum
Tienhuei Yeh
Steven Gillilan
Leslie Collins
Rossy E. Eguigure
Scott Ermisch
Bruce Casino
Sam Harowitz
Ari Tan
Robert Haiat
JC Acosta
Bracken Burns
Stuart Hunter
Can Peker
Zeynep Peker
Onur Peker
Adriana Alvarez
Markus Sebring
Bryan Gabourie
Evan Shapiro
Polly Scates
Tom Brisley
Stephen Dost
Meghan Wurtz
Sonja Chilcott
Herman Campbell
Enad Hijjawi
Odai Hijjawi
Suyeong Kim
Mariya Lyapin
Leela Pon
Arunkanth Venugopal
Edward Seaman
Paul Buccieri
Johanna Veysset
Antonio Hrynchuk
Jeffrey Brazzle
Eloisa Lopez
Bettina Schmucki
Fabrizio Zappi
Anna-Maria Meurman
Erin Tatum
Anna Budashevskaya
Rana Mancini
Lydia Kane
Shaquille Roberts
Angelica Willard
John Sykes
Ángeles Pérez Aguirre
Donna D'Alessandro
Marine Ksadzhikyan
Jeffrey Friedman
Max Einhorn
Lillian Glass
Kathi Chandler-Payatt
Philip Oppenheim
Adam Robinson
Dave Hamilton
Vanessa Bass
Teresita Nunez Perez
Jill Allemand
Natasha Villadolid
Pete Miranti
Monica Veiga
Laki Baker
Mark Lester
Manuel Soto Porcaro
Jemma Yates
Stephen Brown
Erick Opeka
Dionne Gordon
Ayumi Takahira
Steven Saltman
Karen Wheeler
Olga Vafina

Deborah Skeffington
Cida Goncalves
Andres Nieto Serpa
Janice Strangward
Ri-Karlo Handy
Leah Kohn
Danielle Pisano
Rolando Figueroa
Julie Jackson
Felipe Osorio
Leisha Shorey
Mark Garner
Ken Bingham
Joel Dubin
Bruce Orosz
LISSETTE GARCIA ARROGANTE
Mathew Ratner
Catherine Power-Chartrand
Suzanne Astells
Pam Wilson
Cayce Kelly
Rick Barker
Nicky Davies Williams
Leandro Wierna Calderon
Patrick Vien
Maegan McConnell
Heather Wood
Alfonso Haces
Hernán Cerdeiro
Juan Camilo Rodríguez
Niloo Badie
Dade Hayes
Francisco Cordero
Pedro Barbadillo
Javier Yraola
Karen Quinn
Pablo Contreras
Tim Mutimer
Dominic Giannetti
Glen Evelyn
Jennifer Vaux
Gachi Ciurluini
Carmen  Larios 
Peter Gaffney
Alonso Carrillo
Mark Montefiore
Mateus Pagani Muradian
David Elliot-Jones
Ashley Hammen
Liz Levenson
Sophie Ferron
Karreem Lowe
Jay Holzer
Emily Posey Brody
Matias Garay
James McEvoy
Ralf Bartoleit
Steven Green 
Evan Steiner
Robert Friedman
Derrica Wilson
Katrina Kowalski
Terry Adams
Kate Beal
Natalie Wilson
Peter White
Murray Lipnik
Grace Marzella
Sandi Cooper
Balaji Varadhachariyar
Johnny Miles
Bridget Sponsky
Manori Ravindran
Justina Wojtowicz
Justin Rebelo
Shawn White
Ryne Dillon
Darrin Holender
Ryan Sharkey
Dennis Goggin
Julia Dangond
Chip Harwood
Jose Luis Gascue
Francheska Leon de la Barra
Carlos Fernandez
Alejandra Gonzalez Jauregui
Rick De Oliveira
Billy Dundee
Chevonne O'Shaughnessy
MJ Sorenson
Michael Bancroft
Eddy Arias
Stacey Nagel
Cosette Molina
Diane Rankin
Mario Domina
Ellen Lovejoy
Dan Shannon
John Washco
Mack Carroll
Leonardo Pinto
Katie MacIntosh
Caleb Krassner
Matt Harper
Marc HELFRICH
Daniel Mekinda
Daniel Rodriguez
Theo Wolf
Gary Marenzi
Beth Stevenson
Bob Buruchian
Tina Dobbelaere
Patrick Weiland
Sandra Smester
Rhayvnn Drummer
Grace Santos
Fred Smith
Luda Ruditsky
Jeffrey Wank
Paola Gomez
Lisa Doganieri
Lilla Hurst
Minerva Lopez
Seiichi Shinno
Sheila Aguirre
Trey Durst
Michela DiMondo
Shirley Bowers
Lisa Honig
Cynthia Ismino
Olivia LaRoche
Alexandre Kostenko
Michael Holstein
Nicholas Treeshin
Elliot Clark
Beatriz Marfa-Linley
Francys Vallecillo
Rosanna Canonigo
Jasmine  Monet 
David de Bie
Raul Pina
Brian Wahlund
Vikrant Mathur
David Di Lorenzo
Gerry Gershman
John Stack
Steven Menkin
Cassie  Yde
Caley MacLennan
Kevin Leeson
Scarlett Koehne
Derren Lawford
Lisa Ritschel
Ani Khachoian
Michael Imbesi
Gregory Maurice
Barbara Zaneri
Maria Iregui
Bruce Rabinowitz
Anouk van Dijk
Valerie Meraz
Heath Davis
Kirk Coburn
Ceyda Sila Çetinkaya
Dilip Bala
Jerold Anchan
Ludo Dufour
Kerry Deignan Roy
Bianka Krausch
Mike Cosentino
Diana Ariza
Kam Jey
Reinaldo Mendes
Brian Collins
Brenda Garcia
Doug Schwab
Nicola Goelzhaeuser
Zareefa Abdul-Adl
Adam Nicholson
Courtney Hirsch
Xavier Kochhar
Rua Wani
Reem Morsi
Louis Hillelson
Robert Marking
Manuel De Sousa
Riley Weston
Nikki Love
Elizabeth Sheldon
Daniel Tah
Martha Godoy
Craig Urquhart
Paul Coster
Jasmine Allen
Oscar Amador
Sally Ng
Jonathan Plowman
Rosana Sandoval-Gallardo
Fernando Vila
Devin Carter
Samantha Ferguson
Elizabeth Chan
Jose Luis Martinez
Mai Flournoy
Patrick Zuchowicki Jucaud
Evans Butterworth
Luke Willms
Lisa Osinloye
Jonathan Verk
Eric Shamlin
Urania Agas
Shama Johnson
Katherine Cardenas
Vanessa Velazquez
Carlos Mesber
Sebastian Mellino
Maria Muci
Sylvia Viljoen
Viola Zintgraf
Gema Lopez
Lilliam Hernandez
Rosalind Rotundo
Roxana Rotundo
Yolanda Benet
Amanda Ospina
Alejandro Sacasa
Kristen  Eppley
Tom Nowicki
Jon Alwen
Chris Lancey
Bob Seeman
Bo LaMotte
Audrey Kamga
Dan Treinish
Cherie Park
Ignacio Barrera
Duncan McIntosh
Elana Sofko
Tom Devlin
Wendy Thomas
Tim Warren
Arturo Gonzalez
Pablo Cancelliere
Oliver Taprogge
Tomas A. Silva
Sagi Reuven
Dolores Fernandez Alonso
Daniel Segredo
Kevin Cross
Jorge Alberto
Jorge Enrique Fiterre
Rob Lobl
Roberto Kuky Pumar
Sandra Stern
Catherine Warren
Haley Kaufman
Stephen Bowles
Andre Fyffe
Yundi Zhu
Carlos Garde Macías
Steven Bulzoni
Susan Nation
Greg Mullin
Gavin Purcell
Limore Shur
Emily Golden
Maribel Ramos-Weiner
Richard Izarra
Barry Brewer
Margo Plotkin
Lucy Le Gruiec
Jessica Sofarnos
Carolina Jaramillo
Sarah Dawson
Kim Hobbs
Blake Mott
Jocelyn Sabo
Peter  Clark
Jeff Sagansky
Sohail Mardanbeigi
Ani Khostegyan
Katie Deutsch
Robert Dearman
Paula Lomax
Clara Wilkerson
Doris Martinez
Taye Shuayb
Philip Webb
Humberto Ciffoni
Alberto Gomez Paredes
Thierry Delaigues
Jack Oliver
Rika Proffitt
Michael McGuigan
Taylor White
Hashim Williams
Chris Barkoozis
Travis Webb
Jacquelyn Ryan
Chris Pownall
Marc Paneque
Jonathan Hazeldine
Fernando Monzon Fabregat
Said Surucu
Andy  Ruane 
Ross Babbit
Will Gurman
Jonathan Blum
Jim Carroccia
Anne Sittmann
Irwin Inman
Eugene Han
Juan Du
Betsy Green
Jean Rudnick
Wiktor Bilan
Krista Sonne
Jennifer Soltesz
Patricia Motilla
Carl Hall
Kattia Quintanilla
Alastair Cook
Daniela Zulueta
Polina Mladenova
Peter Mcmahon
Jennifer Liang
Nela Pavlouskova
Builder Brock
Yeshuah Castillo
Sebastian Jimenez
Ari Mark
Kunal Wadhwani
Matt Rivet
Mark Dee-Shapland
Andres Santos
Eva Obadia
Allie Dvorin
Carlos Sanchez
Rick Ray
Jessica Saginaw
Andrew Latimer
Rick Bergan
Kevin Sullivan
Sergio Pizzolante
Robyn DeMarco
Manuel Aguilera
Andrea Stokes
Irwin Podhajser
Robert Cervini
Anthony Seratelli
Michele Santiago
Denella Ri'chard
Kimberly Woodard
Greg Henry
Isaac Holub
Erin Spellaza
Valerie Heroux
Kathryn Medellin
Hilda Hagopian
David Fannon
Gabriel Shipton
Betal Ozay
Marcelo Bitelli
Joe Wang
Joseph Scotti
Rick Eldridge
Sarah Bickley
Tanya Low
Austin Ladouceur
Emma Manfredi
Annie O'Brien
Alexandra Panousis
Jennifer Weingroff
Robert Sharenow
Carla Kaufman Sloan
Chris Sloan
Chet Fenster
David Bank
Pluria Marshall Jr
Rick Rodriguez
Shaked Berenson
Barrett Dungy
Jessica Robles
James Patrick
Daniel Palis
Andrew Singer
Oliver DeLuca
Wendy Wang
Jessica Brunton
Alonzo Buchanan Jr.
Todd Mazer
Paulo Koelle
Gave Lindo
Sulaiman Lalani
Fiona McWilliam
Noah Rubenstein
Brad Samuels
Marc Liebmann
Alex Villada
Li Sun
Merve Polat
Jennifer Freeman
David Flores-Sanchez
Mark Koops
Gracia Larrain
Krystyna Hall
Andrea Bravo Puerta
Romina Rosado
Matthew Rosenstein
John Stevens
Cori Abraham
Chantal  Chauzy
Jhamal Robinson
Alfredo Richard
Javier Gore
Dmitry Orekhov
Flavio Morales
Lisa Lew
Betsy Fellner
"""

import re

def extract_names(text):
    # Split the text by newlines and filter out empty lines
    lines = [line.strip() for line in text.split("\n") if line.strip()]
    # Use regex to match names (assuming names consist of letters and spaces)
    names = [line for line in lines if re.match(r'^[A-Za-z\s]+$', line)]
    return names

names = extract_names(names)
count = 1
results = driver.find_elements(By.XPATH, '//div[@class="card"]//div[@class="profiledetails"]//h4')
for result in results:

    if result.text not in names:
        print(f"({count}): {result.text}")
        
    if count >= 1010:
        break
    
    count += 1